# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - stokvel-backed

on:
  push:
    branches:
      - testing
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: npm install, build, and test
        run: |
<<<<<<< HEAD
          cd server
          rm -rf node_modules
          npm install --production
=======
          npm install
          npm run build --if-present
          npm run test --if-present
>>>>>>> 67f44458799aa7e3167af034d65aa4907eef3ce1

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
<<<<<<< HEAD
          path: ./server
=======
          path: .
>>>>>>> 67f44458799aa7e3167af034d65aa4907eef3ce1

  deploy:
    runs-on: ubuntu-latest
    needs: build
<<<<<<< HEAD
    
=======
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

>>>>>>> 67f44458799aa7e3167af034d65aa4907eef3ce1
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
<<<<<<< HEAD
      
      - name: 'Deploy to Azure Web App'
=======
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_57D56717C6E447C5855E170E33F92B03 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_683FCCD735B84C62B5594FC8F1A132AB }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_64FD596B1A6B46AAA3A8793E1B5FD000 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
>>>>>>> 67f44458799aa7e3167af034d65aa4907eef3ce1
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'stokvel-backed'
          slot-name: 'Production'
          package: .
<<<<<<< HEAD
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_76A3371209F54B90835A23ED7E72A1A3 }}
=======
          
>>>>>>> 67f44458799aa7e3167af034d65aa4907eef3ce1
